name: NIGHTLY upload runner data
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_upload_runner_data:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    defaults:
      run:
        shell: bash -leo pipefail {0}
    timeout-minutes: 500
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get current date
        shell: bash
        run: |
          current_date=$(date +'%Y-%m-%d')
          echo "start_date=$current_date" >> "$GITHUB_ENV"

      - name: Add data
        id: add-initial-data
        uses: ./.github/actions/upload-metrics
        with:
          workflow-start-time: ${{ env.start_date }}

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: workflow-report.json
          path: workflow-report.json
          retention-days: 7

    
