name: Registers new devices to the Apple Developer Portal
on:
  workflow_dispatch:
    inputs:
      device_name:
        description: Name your device
        required: true
      device_id:
        description: Enter its Unique Device Identifier (UDID).
        required: true

jobs:
  prechecks:
    name: Pre-Checks
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    outputs:
      device_name: ${{ steps.prechecks.outputs.device_name }}
      device_UDID: ${{ steps.prechecks.outputs.device_UDID }}
    timeout-minutes: 5
    steps:
      - name: Run pre-checks
        id: prechecks
        uses: actions/github-script@v6
        with:
          script: |
            const deviceName = '${{ github.event.inputs.device_name }}'
            const deviceUDID = '${{ github.event.inputs.device_UDID }}'
            if (typeof deviceName === 'undefined'|| deviceName.trim() === '') {
              const message = `👋  @${context.actor}, seems as if the input, `Device Name` contained an invalid answer: '${{ github.event.inputs.device_name }}'.`;
              core.setFailed(message);
              return
            }

            if (typeof deviceUDID === 'undefined'|| deviceUDID.trim() === '') {
              const message = `👋  @${context.actor}, seems as if the input, `Device UDID` contained an invalid answer: '${{ github.event.inputs.deviceUDID }}'.`;
              core.setFailed(message);
              return
            }

            core.setOutput('device_UDID', deviceUDID);
            core.setOutput('device_name', deviceName);
      
      - name: Register Device
        id: register-device
        run: |
          echo ${{ needs.prechecks.outputs.device_UDID }}
          echo ${{ needs.prechecks.outputs.deviceName}}
          echo ${{ job.status }}